adj1 = input("Enter an adjective: ")
adj2 = input("Enter another adjective: ")
bird = input("Enter a type of bird: ")
room = input("Enter a room in a house: ")
past_verb = input("Enter a past tense verb: ")
verb = input("Enter a verb: ")
name = input("Enter a friend's name: ")
noun = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
verbing = input("Enter a verb ending in -ing: ")
body_part = input("Enter a body part (plural): ")
plural_noun = input("Enter a plural noun: ")
verbing2 = input("Enter another verb ending in -ing: ")
noun2 = input("And finally, enter another noun: ")

print("\n\nIt was a " + adj1 + ", cold November day.")
print("I woke up to the " + adj2 + " smell of " + bird + " roasting in the " + room + " downstairs.")
print("I " + past_verb + " down the stairs to see if I could help " + verb + " the dinner.")
print("My mom said, \"See if " + name + " needs a fresh " + noun + ".\"")
print("So I carried a tray of glasses full of " + liquid + " into the " + verbing + " room.")
print("When I got there, I couldn't believe my " + body_part + "!")
print("There were " + plural_noun, verbing2 + " on the " + noun2 + "!")